#############################################################################
# Makefile for building: Wydatnik
# Generated by qmake (2.01a) (Qt 4.7.2) on: niedz. wrz 18 20:05:01 2011
# Project:  Wydatnik.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ QMLJSDEBUGGER_PATH=/usr/share/qtcreator/qml/qmljsdebugger -o Makefile Wydatnik.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_SQL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtSql -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtSql -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		wydatnik.cpp \
		login.cpp \
		registration.cpp \
		rozchody.cpp \
		wykres.cpp \
		mytablewidget.cpp \
		mycheckbox.cpp \
		editdata.cpp moc_wydatnik.cpp \
		moc_login.cpp \
		moc_registration.cpp \
		moc_rozchody.cpp \
		moc_wykres.cpp \
		moc_mytablewidget.cpp \
		moc_editdata.cpp \
		moc_mycheckbox.cpp \
		qrc_ikony.cpp
OBJECTS       = main.o \
		wydatnik.o \
		login.o \
		registration.o \
		rozchody.o \
		wykres.o \
		mytablewidget.o \
		mycheckbox.o \
		editdata.o \
		moc_wydatnik.o \
		moc_login.o \
		moc_registration.o \
		moc_rozchody.o \
		moc_wykres.o \
		moc_mytablewidget.o \
		moc_editdata.o \
		moc_mycheckbox.o \
		qrc_ikony.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		Wydatnik.pro
QMAKE_TARGET  = Wydatnik
DESTDIR       = 
TARGET        = Wydatnik

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_wydatnik.h ui_login.h ui_registration.h ui_rozchody.h ui_editdata.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Wydatnik.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtSql.prl \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ QMLJSDEBUGGER_PATH=/usr/share/qtcreator/qml/qmljsdebugger -o Makefile Wydatnik.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtSql.prl:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ QMLJSDEBUGGER_PATH=/usr/share/qtcreator/qml/qmljsdebugger -o Makefile Wydatnik.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Wydatnik1.0.0 || $(MKDIR) .tmp/Wydatnik1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Wydatnik1.0.0/ && $(COPY_FILE) --parents wydatnik.h login.h registration.h rozchody.h wykres.h obserwator.h obserwowany.h mylabel.h mytablewidget.h editdata.h mycheckbox.h .tmp/Wydatnik1.0.0/ && $(COPY_FILE) --parents icons/ikony.qrc .tmp/Wydatnik1.0.0/ && $(COPY_FILE) --parents main.cpp wydatnik.cpp login.cpp registration.cpp rozchody.cpp wykres.cpp mytablewidget.cpp mycheckbox.cpp editdata.cpp .tmp/Wydatnik1.0.0/ && $(COPY_FILE) --parents wydatnik.ui login.ui registration.ui rozchody.ui editdata.ui .tmp/Wydatnik1.0.0/ && (cd `dirname .tmp/Wydatnik1.0.0` && $(TAR) Wydatnik1.0.0.tar Wydatnik1.0.0 && $(COMPRESS) Wydatnik1.0.0.tar) && $(MOVE) `dirname .tmp/Wydatnik1.0.0`/Wydatnik1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Wydatnik1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_wydatnik.cpp moc_login.cpp moc_registration.cpp moc_rozchody.cpp moc_wykres.cpp moc_mytablewidget.cpp moc_editdata.cpp moc_mycheckbox.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_wydatnik.cpp moc_login.cpp moc_registration.cpp moc_rozchody.cpp moc_wykres.cpp moc_mytablewidget.cpp moc_editdata.cpp moc_mycheckbox.cpp
moc_wydatnik.cpp: login.h \
		wydatnik.h \
		registration.h \
		rozchody.h \
		obserwowany.h \
		obserwator.h \
		wykres.h \
		wydatnik.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) wydatnik.h -o moc_wydatnik.cpp

moc_login.cpp: wydatnik.h \
		login.h \
		registration.h \
		rozchody.h \
		obserwowany.h \
		obserwator.h \
		wykres.h \
		login.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) login.h -o moc_login.cpp

moc_registration.cpp: wydatnik.h \
		login.h \
		registration.h \
		rozchody.h \
		obserwowany.h \
		obserwator.h \
		wykres.h \
		registration.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) registration.h -o moc_registration.cpp

moc_rozchody.cpp: wydatnik.h \
		login.h \
		registration.h \
		rozchody.h \
		obserwowany.h \
		obserwator.h \
		wykres.h \
		rozchody.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) rozchody.h -o moc_rozchody.cpp

moc_wykres.cpp: obserwator.h \
		obserwowany.h \
		wykres.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) wykres.h -o moc_wykres.cpp

moc_mytablewidget.cpp: mytablewidget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mytablewidget.h -o moc_mytablewidget.cpp

moc_editdata.cpp: wydatnik.h \
		login.h \
		registration.h \
		rozchody.h \
		obserwowany.h \
		obserwator.h \
		wykres.h \
		editdata.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) editdata.h -o moc_editdata.cpp

moc_mycheckbox.cpp: mycheckbox.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mycheckbox.h -o moc_mycheckbox.cpp

compiler_rcc_make_all: qrc_ikony.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_ikony.cpp
qrc_ikony.cpp: icons/ikony.qrc \
		icons/calendar_icon_mini.png
	/usr/bin/rcc -name ikony icons/ikony.qrc -o qrc_ikony.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_wydatnik.h ui_login.h ui_registration.h ui_rozchody.h ui_editdata.h
compiler_uic_clean:
	-$(DEL_FILE) ui_wydatnik.h ui_login.h ui_registration.h ui_rozchody.h ui_editdata.h
ui_wydatnik.h: wydatnik.ui \
		mylabel.h \
		obserwator.h \
		obserwowany.h \
		wydatnik.h \
		login.h \
		registration.h \
		rozchody.h \
		wykres.h
	/usr/bin/uic-qt4 wydatnik.ui -o ui_wydatnik.h

ui_login.h: login.ui
	/usr/bin/uic-qt4 login.ui -o ui_login.h

ui_registration.h: registration.ui
	/usr/bin/uic-qt4 registration.ui -o ui_registration.h

ui_rozchody.h: rozchody.ui
	/usr/bin/uic-qt4 rozchody.ui -o ui_rozchody.h

ui_editdata.h: editdata.ui
	/usr/bin/uic-qt4 editdata.ui -o ui_editdata.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp wydatnik.h \
		login.h \
		registration.h \
		rozchody.h \
		obserwowany.h \
		obserwator.h \
		wykres.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

wydatnik.o: wydatnik.cpp wydatnik.h \
		login.h \
		registration.h \
		rozchody.h \
		obserwowany.h \
		obserwator.h \
		wykres.h \
		ui_wydatnik.h \
		mylabel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o wydatnik.o wydatnik.cpp

login.o: login.cpp login.h \
		wydatnik.h \
		registration.h \
		rozchody.h \
		obserwowany.h \
		obserwator.h \
		wykres.h \
		ui_login.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o login.o login.cpp

registration.o: registration.cpp registration.h \
		wydatnik.h \
		login.h \
		rozchody.h \
		obserwowany.h \
		obserwator.h \
		wykres.h \
		ui_registration.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o registration.o registration.cpp

rozchody.o: rozchody.cpp rozchody.h \
		wydatnik.h \
		login.h \
		registration.h \
		wykres.h \
		obserwator.h \
		obserwowany.h \
		ui_rozchody.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rozchody.o rozchody.cpp

wykres.o: wykres.cpp wykres.h \
		obserwator.h \
		obserwowany.h \
		wydatnik.h \
		login.h \
		registration.h \
		rozchody.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o wykres.o wykres.cpp

mytablewidget.o: mytablewidget.cpp mytablewidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mytablewidget.o mytablewidget.cpp

mycheckbox.o: mycheckbox.cpp mycheckbox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mycheckbox.o mycheckbox.cpp

editdata.o: editdata.cpp editdata.h \
		wydatnik.h \
		login.h \
		registration.h \
		rozchody.h \
		obserwowany.h \
		obserwator.h \
		wykres.h \
		ui_editdata.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o editdata.o editdata.cpp

moc_wydatnik.o: moc_wydatnik.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_wydatnik.o moc_wydatnik.cpp

moc_login.o: moc_login.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_login.o moc_login.cpp

moc_registration.o: moc_registration.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_registration.o moc_registration.cpp

moc_rozchody.o: moc_rozchody.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_rozchody.o moc_rozchody.cpp

moc_wykres.o: moc_wykres.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_wykres.o moc_wykres.cpp

moc_mytablewidget.o: moc_mytablewidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mytablewidget.o moc_mytablewidget.cpp

moc_editdata.o: moc_editdata.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_editdata.o moc_editdata.cpp

moc_mycheckbox.o: moc_mycheckbox.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mycheckbox.o moc_mycheckbox.cpp

qrc_ikony.o: qrc_ikony.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_ikony.o qrc_ikony.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

